config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'tasks/index'
  root to: "tasks#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tasks
  has_many :comments

  with_options presence: true do
    validates :name
    validates :title
    validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i }
  end
  validates :email, uniqueness: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :a_word, :title])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  @comment = Comment.new(comment_params)
  if @comment.save
    redirect_to task_path(@comment.task)
  else
    @task = @comment.task
    @comments = @task.comments
    render "tasks/show"
  end
end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, task_id: params[:task_id])
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_prototype, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :move_to_index, only: [:edit, :update, :destroy]
  
  def index
    @tasks = Task.all.includes(:user).order("created_at DESC")
  end
  
  def new
    @task = Task.new
  end
  
  def create
    @task = Task.new(Task_params)
    if @task.save
      redirect_to root_path
    else
      render :new
    end
  end
  
  def show
    @comment = Comment.new
    @comments = @task.comments.includes(:user)
  end
  
  def update
    if @task.update(task_params)
      redirect_to task_path
    else
      render :edit
    end
  end
  
  def destroy
    if @task.destroy
      redirect_to root_path
    else
      render :index
    end
  end
  
  private
  
  def task_params
    params.require(:task).permit(:title, :catch_copy, :concept, :image).merge(user_id: current_user.id)
  end
  
  def set_task
    @task = Task.find(params[:id])
  end
  
  def move_to_index
    redirect_to root_path unless current_user == @task.user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @name = @user.name
    @tasks = @user.tasks
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>ProtoSpace</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("tasque.png", class: :logo), root_path %>
          </div>
          <% if user_signed_in? %>
            <div class="nav__right">
              <%= link_to "冒険の書を閉じる", destroy_user_session_path, class: :nav__logout, method: :delete %>
              <%= link_to "タスクを投稿する", new_prototype_path, class: :nav__btn %>
            </div>
          <% else %>
            <div class="nav__right">
              <%= link_to "冒険の書を開く", new_user_session_path, class: :nav__btn %>
              <%= link_to "冒険の書を作成", new_user_registration_path, class: :nav__btn %>
            </div>
          <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright"></p>
    </footer>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with model: @task, local: true do |f|%>
  <div class="field">
    <%= f.label :title, "プロトタイプの名称" %><br />
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :catch_copy, "キャッチコピー" %><br />
    <%= f.text_area :catch_copy, class: :form__text %>
  </div>

  <div class="field">
    <%= f.label :concept, "コンセプト" %><br />
    <%= f.text_area :concept, class: :form__text %>
  </div>

  <div class="field">
    <%= f.label :image, "タスクイメージ" %><br />
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<div class="card">
  <%= link_to image_tag(task.image, class: :card__img ), task_path(task.id)%>
  <div class="card__body">
    <%= link_to task.title, task_path(task.id), class: :card__title%>
    <p class="card__summary">
      <%= task.catch_copy %>
    </p>
    <%= link_to "by #{task.user.name}", task_path(task.id), class: :card__user %>
  </div>
</div>

app/views/tasks/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">プロトタイプ編集</h2>
      <%= render partial: "form", locals: { task: @task } %>
    </div>
  </div>
</div>

app/views/tasks/index.html.erb
<main class="main">
  <div class="inner">

    <% if user_signed_in? %>
      <div class="greeting">
        今日も頑張りましょう!!
        <%= link_to current_user.name, user_path(current_user.id), class: :greeting__link %>さん
      </div>
    <% end %>
    <div class="card__wrapper">
      <%= render partial: "task", collection: @tasks, locals: { task: @task } %>
    </div>
    
  </div>
</main>

app/views/tasks/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">新規タスクの投稿</h2>
        <%= render partial: "form", locals: { task: @task } %>
    </div>
  </div>
</div>

app/views/tasks/show.html.erb
<main class="main">
  <div class="inner">
    <div class="task__wrapper">
      <p class="task__hedding">
        <%= @task.title %>
      </p>
      <%= link_to "by #{@task.user.name}", user_path(@task.user_id), class: :task__user %>
      <% if user_signed_in? && current_user.id == @task.user_id %>
        <div class="task__manage">
          <%= link_to "編集する", edit_task_path(@task.id), class: :task__btn %>
          <%= link_to "削除する", task_path(@task.id), method: :delete, class: :task__btn %>
        </div>
      <% end %>
      <div class="task__image">
        <%= image_tag @task.image %>
      </div>
      <div class="task__body">
        <div class="task__detail">
          <p class="detail__title">キャッチコピー</p>
          <p class="detail__message">
            <%= @task.catch_copy %>
          </p>
        </div>
        <div class="task__detail">
          <p class="detail__title">コンセプト</p>
          <p class="detail__message">
            <%= @task.concept %>
          </p>
        </div>
      </div>
      <div class="task__comments">
        <% if user_signed_in? %>
          <%= form_with(model: [@task, @comment], local: true) do |f| %>
            <div class="field">
              <%= f.label :text, "コメント" %><br />
              <%= f.text_field :text %>
            </div>
            <div class="actions">
              <%= f.submit "送信する", class: :form__btn  %>
            </div>
          <% end %> 
        <% end %>
        <ul class="comments_lists">
          <% @comments.each do |comment| %>
            <li class="comments_list">
            <% if @comments %>
              <%= comment.text%>
              <%= link_to comment.user.name, user_path(comment.user.id), class: :comment_user %>
            <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
        <%= @name %>さんの情報
      </h2>
      <table class="table">
        <tbody>
          <tr>
            <th class="table__col1">名前</th>
            <td class="table__col2"><%= @name %></td>
          </tr>
          <tr>
            <th class="table__col1">プロフィール</th>
            <td class="table__col2"><%= @user.profile %></td>
          </tr>
          <tr>
            <th class="table__col1">所属</th>
            <td class="table__col2"><%= @user.occupation %></td>
          </tr>
          <tr>
            <th class="table__col1">役職</th>
            <td class="table__col2"><%= @user.position %></td>
          </tr>
        </tbody>
      </table>
      <h2 class="page-heading">
        <%= @name %>さんの今日のタスク
      </h2>
      <div class="user__card">
        <%= render partial: "tasks/task", collection: @tasks, locals: { task: @task } %>
      </div>
    </div>
  </div>
</div>